services:
  db_postgres:
    image: postgres:17
    container_name: db_postgres
    environment:
      POSTGRES_DB: bank_service
      POSTGRES_USER: bank_app_user
      POSTGRES_PASSWORD: 7fHz8b
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bank_app_user -d bank_service" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  bank-service:
    build: .
    container_name: bank-service
    depends_on:
      db_postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: java -jar /app/service.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/bank_service
      - SPRING_DATASOURCE_USERNAME=bank_app_user
      - SPRING_DATASOURCE_PASSWORD=7fHz8b
      - SPRING_LIQUIBASE_ENABLED=true

volumes:
  postgres_data: