#
# application.yml — главный конфигурационный файл Spring Boot.

bank:
  security:
    jwt_secret_key: "B3yGhFwQ3fZfeaFZugQLCni1"
    jwt_life_time: 1800000

# Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

