spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_service
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: Bank_REST

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  swagger-ui:
    enabled: true

bank:
  security:
    jwt_secret_key: "mpGBWw4FCX68xYUKCYXtEw3zjNrdH3SE"
    jwt_life_time: 1800000
    encryption_key: "Bm2x9jMYWL4awra3LzeSWhBEMmpRUeG2"

server:
  port: 8080